<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="12.0.1" />
        <PackageReference Include="Avalonia.Themes.Fluent" Version="12.0.1" />
        <PackageReference Include="Avalonia.Fonts.Inter" Version="12.0.1" />
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
        <PackageReference Include="AvaloniaUI.DiagnosticsSupport" Version="2.2.1">
            <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
            <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.7" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\TripCostSplitter.AppBase\TripCostSplitter.AppBase.csproj" />
    </ItemGroup>
</Project>
